### ISSUE TITLE
Functionality of :NERDTreeFind

### ISSUE THREAD

**Issue by ArnisL** [troydm/easytree.vim#14]
In NERDTree it's possible to easily jump to currently opened file. I find it really handy.

Is it possible in EasyTree?

**Comment by troydm** [comment]
there is no such functionality in EasyTree however if you type :EasyTree nameofthefileyouhaveopen it will open a directory containing this file. I'll investigate the functionality you've mentioned in NERDTree and see if it's possible to implement in EasyTree

**Comment by ArnisL** [comment]
Thanks a lot. In case you find it unnecessary or something, would greatly appreciate some kind of hackish version or just some vague implementation directions :)

**Comment by troydm** [comment]
can you describe me how to use that functionality in NERDTree? I'm not too expert in NERDTree and haven't used it in a while since I wrote EasyTree

**Comment by ArnisL** [comment]
i got this mapped:
nmap <A-L> :NERDTreeFind<CR>
(needs some extra stuff for ALT to work, but that's not the point)

since i do use CTRL-P fuzzy search file finder, sometimes it's handy to hit Alt+L to jump into NERDTree where the file is located

anyway, usage is simple:
1. open any file
2. write ":NERDTreeFind" and hit enter
3. nerdtree should pop up and navigate to opened file

**Comment by troydm** [comment]
try to see if it meets your requirments
:noremap <A-l> :exe ':EasyTree '.expand('%:p:h')<CR>

**Comment by ArnisL** [comment]
Not entirely. Would be nice if it kept root directory and navigated cursor to exact line.

Anyway - good enough. Thanks.
