### ISSUE TITLE
Request: change Key for CreateFile

### ISSUE THREAD

**Issue by phux** [troydm/easytree.vim#16]
`m` is not mnemonic for creating a file plus conflicts with possible `MoveFiles` functionality.

Request: change default mapping for CreateFile to `a`.
`a` is way closer to the actual behavior of **a**dding a file/dir.

What do you think?

**Comment by troydm** [comment]
well m is actually short for menu and it's how files are created in NERDTree but since we don't use a we can add additional mapping for adding files using a key, I will add this
