### ISSUE TITLE
vcs integration by plugin

### ISSUE THREAD

**Issue by albfan** [troydm/easytree.vim#21]
I'm maintainer of [albfan/nerdtree-git-plugin](https://github.com/albfan/nerdtree-git-plugin)

As you now [nerdtree plugin](https://github.com/scrooloose/nerdtree) is a project drawer with lot of traction.

Its plugin api allows to extend it easily as [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)

I forked nerdtree-git-plugin to allow it to hide files based on file status, and it is a primary plugin on my workflow

Sadly as you now NERDTree performs really bad and slow down all vim when project overpass tens of files.

I have ported your plugin to python3 #20 and it performs dawn fast, great! so I will port my plugin inside yours. Seems an easy task

Just want to know if you have interest on:

- Plugin system for easytree: so you can extend it for any other use
    - icons for dirs and files
    - custom formatters
    - show/hide nodes
    - custom sorting
    - adding virtual nodes (listing different unrelated dirs)
- Helping or designing vcs integration

I will get progress on my fork and try to push upstream, but if you want to define milestones or priorities that would help to ease the pushes

**Comment by albfan** [comment]
Here is a first implementation (flagging nodes if touched)

https://github.com/albfan/easytree.vim/commit/66fcd6a5c70cca8e9df84e2b2a16ba5a44dc5891

filter is almost done

**Comment by albfan** [comment]
Just add an open buffers filter, so although filtering untouched files, it should show open buffers after a refresh

**Comment by troydm** [comment]
@albfan Thank you for your contribution, based on your idea and some of your code I've implemented both Python 3  and Git status indicators support, albeit it's a bit different compared to what you have done but still, I'm closing this issue

**Comment by albfan** [comment]
Nice. Will check if I can rebase my fork on top of that!
