### ISSUE TITLE
[feature] Can it get remote file tree

### ISSUE THREAD

**Issue by tenfyzhong** [troydm/easytree.vim#23]
1. use ssh to get the file tree
1. use sftp to get a file
1. use sftp to send back a file

**Comment by troydm** [comment]
To actually implement this will require a lot of changes in easytree.vim and in result wouldn't even be ideal and will overcomplicate the source code and will make it hard to maintain thus loosing what easytree.vim is supposed to be, a simple tool to do just the task it's meant to be used for, what you can currently do is use sshfs https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh
