### ISSUE TITLE
Adding daily basis helpful commands

### ISSUE THREAD

**Issue by albfan** [troydm/easytree.vim#25]
I just added to my fork a series of commands:

    :EasyTreeFocus
    :EasyTreeLocateCurrentFile
    :EasyTreeRefreshAll

That almost solves my needs for regular usage. I link them to my particular mapping structure to be really helpful but that's too much subjetive

It is heavily based on `g:easytree_toggle_win`, if do you find any of them interesting, just let me know

**Comment by troydm** [comment]
@albfan Added this commands also implementations are a bit different tho, didn't add RefreshAll which is a bit specific to your scenario but can easily be added by combining Focus and R key press, something like

    nnoremap <Leader>r :EasyTreeFocus | normal! R<CR>
