### ISSUE TITLE
Feature request: reveal file in :EasyTree

### ISSUE THREAD

**Issue by bbtdev** [troydm/easytree.vim#26]
Hello,

Any plans to have a reveal functionality, where when on a buffer it can show the location in the tree?

**Comment by troydm** [comment]
@bbtdev please clarify in more detail how this should work. also what would happen if file is in a node that is currently closed? should it autopen all preceding nodes in order to reveal the file location?

**Comment by troydm** [comment]
@bbtdev sorry for long delay, I've almost forgot about this request of yours, so finally found time to add this command called EasyTreeBufferReveal along with some bunch of irrelevant stuff
