### ISSUE TITLE
missing branch symbol 

### ISSUE THREAD

**Issue by albfan** [troydm/easytree.vim#28]
This is how I see the branch symbol:

![Captura desde 2022-08-06 14-27-38](https://user-images.githubusercontent.com/220968/183248946-5d53c8a7-327a-407c-9905-e4adb012a774.png)

Not sure what is the expected unicode symbol

If this works correctly for you maybe we can add some config depending on system.

This could be a good option:
 ⎇'

This is not show on my laptop (maybe is the one you use
 

0xe0a0

![image](https://user-images.githubusercontent.com/220968/183249082-2df253ed-1c80-47db-b192-4ddc56ba36b8.png)

**Comment by troydm** [comment]
@albfan good point, I use nerdfont and it works fine with it, will make it configurable
