### ISSUE TITLE
Possibility for customization of key maps and exposure of command API

### ISSUE THREAD

**Issue by jeetsukumaran** [troydm/easytree.vim#8]
Is it possible to expose internal functions, either as commands or <PLUG>, so we can map custom commands from the easytree buffer? E.g., it would be nice to use <C-V> to open file in new vertical split and close easytree, <C-S> for the same in a new horizontal split, and <C-T> for the same in a new tab (i.e., following CtrlP).

**Comment by troydm** [comment]
wouldn't adding auto close easytree option suffice? like when you open the file to automaticly close easytree window if you have that option enabled?

**Comment by troydm** [comment]
closing this, if it's still relevant please reopen
